### ISSUE TITLE
Wrong css propery for td.today:before

### ISSUE THREAD

**Issue by alexantr** [Eonasdan/bootstrap-datetimepicker#1184]
Browsers don't show corner for today with this short syntax:
```css
.bootstrap-datetimepicker-widget table td.today:before {
    ...
    border: 0 0 7px 7px solid transparent;
    ...
}
```
Must be corrected. Like this:
```css
.bootstrap-datetimepicker-widget table td.today:before {
    ...
    border-width: 0 0 7px 7px;
    border-style: solid;
    border-color: transparent;
    ...
}
```
Or this:
```css
.bootstrap-datetimepicker-widget table td.today:before {
    ...
    border: 7px solid transparent;
    border-top-width: 0;
    border-right-width: 0;
    ...
}
```
