### ISSUE TITLE
Add option for icon labels

### ISSUE THREAD

**Issue by RomeroMsk** [Eonasdan/bootstrap-datetimepicker#1285]
Can you add an option to set icon labels?
Something like this:

``` javascript
iconLabels: {
    today: 'Today',
    clear: 'Clear'
}
```

To get this:
![image](https://cloud.githubusercontent.com/assets/4639951/9466175/488a7fe8-4b4c-11e5-8a7f-b8ad9abd6917.png)

**Comment by pgifford** [comment]
I add labels in the `dp.show` event handler, for example, adding a label to the "close" icon:

```javascript
$('#myEl').find('span.glyphicon-remove').after('<span>Close</span>');
```
Also required is a CSS change:

```css
.bootstrap-datetimepicker-widget table td span {
    display: inline;
}
```

Of course if you use different icons then change the class selector in `find()` accordingly.
