### ISSUE TITLE
Sass error

### ISSUE THREAD

**Issue by Delagen** [Eonasdan/bootstrap-datetimepicker#1736]
What the case of plus sign in 272 line of src/sass/_bootstrap-datetimepicker.scss ???

**Comment by jonatanjohnsson** [comment]
Yes, the latest release on npm includes a sass error which breaks pretty much everything. There's a + on line 272.

in `bootstrap-datetimepicker/src/sass/_bootstrap-datetimepicker.scss`

```css
&.today {
                position: relative;

                &:before {
                    content: '';
                    display: inline-block;
                    border: solid transparent;
 +                  border-width: 0 0 7px 7px;
                    border-bottom-color: $bs-datetimepicker-active-bg;
                    border-top-color: $bs-datetimepicker-secondary-border-color-rgba;
                    position: absolute;
                    bottom: 4px;
                    right: 4px;
                }
            }
```
