### ISSUE TITLE
Layout of "am/pm" button falls outside the widget

### ISSUE THREAD

**Issue by gwynjudd** [Eonasdan/bootstrap-datetimepicker#815]
See the fiddle for an example:

http://jsfiddle.net/a6pdgq1c/

Click on the icon to dropdown the widget, then click on the clock to show the time layout. The "AM/PM" button draws outside the bounds of the widget.

![image](https://cloud.githubusercontent.com/assets/314188/6033981/fa0a5cf8-ac81-11e4-9c11-72e282a967ab.png)

**Comment by Eonasdan** [comment]
Please check the development branch.

**Comment by gwynjudd** [comment]
Looks good to me

**Comment by jarrodbell** [comment]
Need to add a few more CSS media queries to fix the same problem when using sideBySide: true

```css
@media (min-width: 768px) {
  .bootstrap-datetimepicker-widget.dropdown-menu.timepicker-sbs {
    width: 38em;
  }
  .bootstrap-datetimepicker-widget.dropdown-menu.timepicker-sbs.wider {
    width: 42em;
  }
}
@media (min-width: 992px) {
  .bootstrap-datetimepicker-widget.dropdown-menu.timepicker-sbs {
    width: 38em;
  }
  .bootstrap-datetimepicker-widget.dropdown-menu.timepicker-sbs.wider {
    width: 42em;
  }
}
@media (min-width: 1200px) {
  .bootstrap-datetimepicker-widget.dropdown-menu.timepicker-sbs {
    width: 38em;
  }
  .bootstrap-datetimepicker-widget.dropdown-menu.timepicker-sbs.wider {
    width: 42em;
  }
}
```
